name: Deploy to AWS ECS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: DEBUG Print ECR variables
        run: |
          echo "AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}'"
          
          echo "AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}'"
          echo "AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}'"
          echo "AWS_REGION='${{ secrets.AWS_REGION }}'"
          echo "ECR_REPO_FLASK_API='${{ secrets.ECR_REPO_FLASK_API }}'"
          echo "ECR_REPO_STREAMLIT_UI='${{ secrets.ECR_REPO_STREAMLIT_UI }}'"
          echo "ECS_CLUSTER='${{ secrets.ECS_CLUSTER }}'"
          echo "ECS_SERVICE_FLASK='${{ secrets.ECS_SERVICE_FLASK }}'"
          echo "ECS_SERVICE_STREAMLIT='${{ secrets.ECS_SERVICE_STREAMLIT }}'"
          echo "AWS_ACCOUNT_ID='${{ secrets.AWS_ACCOUNT_ID }}'"

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS \
              --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Flask API image
        run: docker build -t text-api ./flask-api

      - name: Tag Flask API image
        run: |
          docker tag text-api:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_FLASK_API }}:latest

      # ... the rest of your pipeline steps
